image:
  pullPolicy: IfNotPresent
  repository: robpearson/gitops-simple-app
  tag: "3.0"

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: financia-web-test.robpearson
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

service:
  type: NodePort
  port: 8080
  nodePort: 32002
