apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: triton-key-development
  namespace: argocd
  annotations:
    argo.octopus.com/project: "triton-key"
    argo.octopus.com/environment: "development"
    argo.octopus.com/instance: "demo.octopus.app"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: triton-key-dev
  sources:
    - repoURL: oci://ghcr.io/robpearson/triton-key-chart
      targetRevision: 0.4.13
      path: .
      helm:
        valueFiles:
          - values.yaml
          - $values-source/triton-key/dev/values.yaml
    - repoURL: https://github.com/robpearson/kubernetes-helm-values.git
      targetRevision: HEAD
      ref: values-source
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
