image:
  pullPolicy: IfNotPresent
  repository: robpearson/seascape-core
  tag: "2026.03.04.76"

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: seascape-core-dev.robpearson
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

service:
  type: NodePort
  port: 8080
  nodePort: 30608
